---
title: "IDFs para a bacia do rio Sousa na zona da Senhora do Salto"
author: "JM Delgado"
date: "`r Sys.Date()`"
output:
  slidy_presentation:
    duration: 5    
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Carregar bacia e definir o centróide e área

```{r results='asis', warning=FALSE, message=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(sf,warn.conflicts=FALSE)
library(dplyr,warn.conflicts=FALSE)
library(knitr,warn.conflicts=FALSE)
library(idf)

ponto=st_centroid(bacia)

area=st_area(bacia)
```

# Definir tempo de concentração e período de retorno


```{r results='asis', warning=FALSE, message=FALSE}
d=lubridate::as.duration(185*60)            # atribuir valor do tempo de concentração
f=100                                      # período de retorno
```

# Aplicar IDFs e estimar

```{r results='asis', warning=FALSE, message=FALSE}
i=df2i(d,f,ponto)                      # intensidade em mm/h
units(i) = with(units::ud_units,m/s)       # converter para unidades SI
C=0.4 # para bacia predominantemente agrícola                                   
q = C*i*area
q
```
